name: Gatsby CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

env:
  HOMOLOG_DOMAIN: http://rapid-cave-hml.surge.sh/
  PRODUCTION_DOMAIN: http://rapid-cave.surge.sh/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build website
        run: |
          echo ${{ github.sha }}
          gatsby build
          sed -i "s/%%VERSION%%/${{ github.sha }}/" ./my-app/public/index.html
        working-directory: ./my-app

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            ./my-app/public
            ./my-app/.cache

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test artifact
        run: grep -q "Gatsby" ./my-app/public/index.html
        working-directory: ./my-app

      - name: Test website
        run: |
          npm install
          npm install -g gatsby-cli
          gatsby serve &
          sleep 3
          curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"
        working-directory: ./my-app

  deploy-review:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    environment:
      name: review/${{ github.head_ref }}
      url: https://rapid-cave-${{ env.GITHUB_HEAD_REF_SLUG }}.surge.sh
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to review environment
        run: surge --project ./my-app/public --domain ${{ env.HOMOLOG_DOMAIN }}

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    environment:
      name: staging
      url: http://${{ env.HOMOLOG_DOMAIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to staging environment
        run: surge --project ./my-app/public --domain ${{ env.HOMOLOG_DOMAIN }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    environment:
      name: production
      url: http://${{ env.PRODUCTION_DOMAIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to production environment
        run: surge --project ./my-app/public --domain ${{ env.PRODUCTION_DOMAIN }}
  production-tests:
    runs-on: ubuntu-latest
    needs: deploy-production
    steps:
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Test production environment
        run: |
          curl -s "https://${{ secrets.PRODUCTION_DOMAIN }}" | grep "${{ github.sha }}"
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}


