name: Gatsby CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

env:
  SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
  SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
  HOMOLOG_DOMAIN: http://rapid-cave-hml.surge.sh/
  PRODUCTION_DOMAIN: http://rapid-cave.surge.sh/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build website
        run: |
          echo ${{ github.sha }}
          gatsby build
          sed -i "s/%%VERSION%%/${{ github.sha }}/" ./public/index.html
        

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: | 
            ./public
            ./.cache

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: website
      - name: Test artifact
        run: |
          grep -q "Gatsby" ./public/index.html
      - name: Test website
        run: |
          npm install
          npm install -g gatsby-cli
          gatsby serve &
          sleep 3
          curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"
        working-directory: .
        continue-on-error: true  
        

  deploy-review:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    environment:
      name: review/${{ github.head_ref }}
      url: https://rapid-cave-${{ env.GITHUB_HEAD_REF_SLUG }}.surge.sh
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to review environment
        run: surge --project "./public" --domain ${{ env.HOMOLOG_DOMAIN }}
        working-directory: . 

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    environment:
      name: staging
      url: http://${{ env.HOMOLOG_DOMAIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to staging environment
        run: surge --project ./public --domain ${{ env.HOMOLOG_DOMAIN }}
        working-directory: . 

  deploy-production:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    environment:
      name: production
      url: http://${{ env.PRODUCTION_DOMAIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to production environment
        run: surge --project ./public --domain ${{ env.PRODUCTION_DOMAIN }}
        working-directory: . 
      
        
  production-tests:
    runs-on: ubuntu-latest
    needs: deploy-production
    steps:
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Test production environment
        run: |
          curl -s "https://${{ secrets.PRODUCTION_DOMAIN }}" | grep "${{ github.sha }}"
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}


